[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit BME280 Library @ ^2.3.0
	adafruit/Adafruit Unified Sensor @ ^1.1.15

build_flags = 
	-DPOST_DELAY_MS=10000
	; ESP-NOW enabled
	-DESPNOW_ENABLED
	-DESPNOW_NODE=\"aa:aa:aa:aa:aa:aa\"
	; ESP-NOW disabled
	; omit enabled flag
	-DWIFI_SSID=\"ssid\"
	-DWIFI_PASS=\"password\"
	-DSERVER_URL=\"http://localhost:8080/update/outdoor\"
	-DAPI_KEY=\"key\"