services:
  grafana-init:
    image: alpine
    container_name: grafana-init
    user: root
    volumes:
      - ./grafana-storage:/var/lib/grafana
    command: chown -R 472:472 /var/lib/grafana

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      grafana-init:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - default
      - timescaledb_net

volumes:
  grafana-storage:

networks:
  timescaledb_net:
    external: true
    name: timescaledb_default
